### ISSUE TITLE
Multi action interference

### ISSUE THREAD

**Issue by marcvillanuevamir** [kimballa/button-debounce#5]
Hi @kimballa ! Thank you very much for your development and support! I come back to this thread because I am using your multi action button example, but I'd like it to effectively switch between different actions without triggering other actions. For that, it would make sense for me to trigger the action on button release, but as soon as I release the long push button, the short push button gets triggered as well. I have been trying to flag them to not much avail, so I'd be grateful if you could give me a hint or provide an example where different actions don't interfere with each other. Thank you so much!

_Originally posted by @marcvillanuevamir in https://github.com/kimballa/button-debounce/issues/3#issuecomment-2311893327_

**Comment by kimballa** [comment]
Hi Marc,

Handle both actions on release. Have a global `useShort` boolean set to true when the short action is pushed and false when the long action push event occurs.

The short action onRelease only does stuff when useShort is true; the long press onRelease action only does stuff when useShort is false.

I think that'll get you where you need to go.

**Comment by marcvillanuevamir** [comment]
Oh yes! That workes! Thank you so much :)
